### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by guoyanb** [MinZeng1990/A_deep_learning_framework_for_identifying_essential_proteins#1]
Hello!
Your work is great and I am very interested in your work. Can you give a detailed description of your data set? Or the raw data?

**Comment by MinZeng1990** [comment]
Hello!
Thank you for your attention! 

I give four npy files in this project as follows: 
protein_emb.npy is the 64-dimensional vector which is generated by node2vec by using PPI network. Its shape is 5297 proteins x 64 features.
protein_matrix.npy is the gene expression data and we reshape it to 5297 proteins x 3 cycles x 12 time points.
protein_loc.npy is the protein subcellular localization data.
protein_label.npy is the labels of proteins (1:essential proteins and 0: non-essential proteins). 

You can read my paper. Here is the link: https://ieeexplore.ieee.org/abstract/document/8634927

If you have any questions, you can leave me messages.

**Comment by guoyanb** [comment]
@MinZeng1990. I am confused about the following questions, could you please give me a  description？ Thanks!
In Section data sources, 1) the data of PPI consists of 5616 proteins and 1199 essential proteins, however, in Section implementation details, it consits of 5297 proteins and 1185 esstential proteins; 2) the data of gene expression contains 6777 proteins and the data of subcellular localization contains 3923 proteins, however, in Section implementation details, they contain 5297 proteins.

**Comment by MinZeng1990** [comment]
In the section of data source, I describe the raw datasets; and in the section of implementation details, I describe the truely use of datasets. Why the number in the section of implementation details is less than the number in the section of data source? Because not each protein in our PPI network has corresponding gene expression profile. Thus, we filter some proteins, we only choose proteins in our PPI network which have gene expression profile. You can see the protein_emb.npy and protein_matrix.npy files, they all have 5297 protein samples.

**Comment by guoyanb** [comment]
@MinZeng1990 Ok, thank you for your reply !

**Comment by MinZeng1990** [comment]
@guoyanb You are welcome！~^o^~
